### ISSUE TITLE
Invalid Syntax

### ISSUE THREAD

**Issue by CookieAvenger** [agateau/yokadi#58]
when I run yokadi in ubuntu 16.04 (got the program from official universe archives) - I get - 

> $ yokadi
> Traceback (most recent call last):
>   File "/usr/local/bin/yokadi", line 17, in <module>
>     from yokadi.ycli import main
>   File "/usr/local/lib/python2.7/dist-packages/yokadi/ycli/main.py", line 126
>     print("**\* I/O error ***\n\t%s" % e, file=sys.stderr)
>                                              ^
> SyntaxError: invalid syntax

note: it pasted differently to what I got from terminal the "^" should be underneath the "=" in "file=sys.stderr"

I don't know any python, So for a few months now I've just been patiently waiting for this to go away, but it seems no one else has reported it yet, so here I am. Can you please fix this, I'm still curious to know what this program can do for me.

shown in attachment below
![screenshot from 2016-10-06 16-07-11](https://cloud.githubusercontent.com/assets/18612627/19142190/fc7dbd34-8bde-11e6-9ec5-5f8fc69ab2f2.png)

**Comment by agateau** [comment]
The Yokadi binary you ran is in /usr/local/bin. This indicates that it was installed by hand. The Yokadi binary provided by the packages would be in /usr/bin.

Since version 1.0.0, Yokadi requires Python 3. The error you received happens when one tries to run Python 3 code with Python 2.

What I suggest you do is:

- Uninstall the Ubuntu package, it's old: (`sudo apt remove yokadi`)

- Uninstall the manually installed local version with:
```
cd /usr/local
sudo rm -rf lib/python*/dist-packages/yokadi
sudo rm -rf share/yokadi
sudo rm bin/yokadi*
```

- Install the latest version of Yokadi with `sudo pip3 install yokadi`. If you get an error saying that pip3 is not installed, install pip3 with `sudo apt install python3-pip` and try again.

**Comment by CookieAvenger** [comment]
Sorry for late response, but thanks to your advice it got fixed, thanks alot :)
